# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-16 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soilMoisture', models.FloatField(null=True)),
                ('read_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='plantID',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('read_time', models.DateTimeField(auto_now=True)),
                ('plantName', models.CharField(max_length=25, null=True)),
                ('latitude', models.FloatField(default=13.5548)),
                ('longitude', models.FloatField(default=80.027)),
            ],
        ),
        migrations.CreateModel(
            name='weatherStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_time', models.DateTimeField(auto_now=True)),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('overHeadTank', models.FloatField(default=0)),
                ('rainGauge', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.plantID'),
        ),
    ]
