# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-18 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherstation',
            name='rainGauge',
            field=models.FloatField(null=True),
        ),
    ]
